### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chenshupe** [GroupMountain/FloatingText#1]
概率遇到破损数据包
服务器一直保持开启 过段时间后再去看浮空字会自动消失，使用reload可以重新加载出来 后台无报错
以上报错只添加了静态浮空字 没有使用变量

**Comment by yufengya0420** [comment]
> 概率遇到破损数据包
> 服务器一直保持开启 过段时间后再去看浮空字会自动消失，使用reload可以重新加载出来 后台无报错
> 以上报错只添加了静态浮空字 没有使用变量

动态悬浮字也有同样的情况

**Comment by Tsubasa6848** [comment]
> > 概率遇到破损数据包
> > 服务器一直保持开启 过段时间后再去看浮空字会自动消失，使用reload可以重新加载出来 后台无报错
> > 以上报错只添加了静态浮空字 没有使用变量
> 
> 动态悬浮字也有同样的情况

@yufengya0420 @chenshupe 以上问题由GMLIB接口问题引起，已在GMLIB修复
